### PR TITLE
Update the build process

### PR DESCRIPTION
**Pull request by jdillard**
## Summary of Changes

- Use `pyproject.toml` and where necessary, `setup.cfg`.
- Use `python -m build`

### CODE REVIEW

**Comment by stevepiercy** [comment]
Will this PR fix the deprecation notice?

> DEPRECATION: sphinx-sitemap is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

If not I can file a new issue. Please let me know. Thank you!

**Comment by jdillard** [comment]
It should, is there a way I can replicate the current deprecation notice?

**Comment by stevepiercy** [comment]
Here's an example GHA build:

https://github.com/plone/documentation/actions/runs/3749024374/jobs/6367030809#step:5:126

And to build the Plone docs locally, you can follow our guide:

https://6.docs.plone.org/contributing/setup-build.html

Pretty much, clone and `make html`, and you're done. You can skip installing Vale.

**Comment by stevepiercy** [comment]
BTW, the maintainer of livereload just uploaded a wheel, we now install `wheel` in our requirements, and the deprecation notice for that package went away. See https://github.com/plone/documentation/issues/1395 and https://github.com/lepture/python-livereload/issues/240

**Comment by jdillard** [comment]
I just released a new version and the [2.3.0 files](https://pypi.org/project/sphinx-sitemap/2.3.0/#files) show a `.whl` now, this should fix your issue. Thanks for pointing that out!

**Comment by stevepiercy** [comment]
Thank you for the quick response!

**Pull request merged**
